// Extended community data with more discussions, news, and interactions
export const communityDiscussions = [
  {
    id: "1",
    title: "Bagaimana mengoptimalkan algoritma machine learning untuk dataset kecil?",
    author: {
      name: "Dr. Sarah Wijaya",
      username: "sarah_wijaya",
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face",
      role: "AI Researcher",
      institution: "Institut Teknologi Bandung",
      reputation: 2450,
      badge: "Expert",
      verified: true,
    },
    category: "Artificial Intelligence",
    content:
      "Saya sedang mengerjakan proyek AI untuk deteksi penyakit tanaman, namun dataset yang tersedia terbatas. Ada yang punya pengalaman dengan teknik data augmentation atau transfer learning untuk kasus seperti ini?",
    stats: {
      likes: 24,
      replies: 12,
      views: 156,
      bookmarks: 8,
    },
    tags: ["machine-learning", "dataset", "ai", "computer-vision"],
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
    isHot: true,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T14:20:00Z",
    lastActivityBy: "Dr. Maya Sari",
  },
  {
    id: "2",
    title: "Mencari kolaborator untuk riset renewable energy di Indonesia",
    author: {
      name: "Prof. Ahmad Fauzi",
      username: "ahmad_fauzi",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      role: "Energy Researcher",
      institution: "Institut Teknologi Bandung",
      reputation: 3200,
      badge: "Mentor",
      verified: true,
    },
    category: "Renewable Energy",
    content:
      "Kami sedang mengembangkan teknologi solar panel dengan efisiensi tinggi. Mencari peneliti yang berpengalaman dalam material science dan engineering untuk bergabung dalam tim.",
    stats: {
      likes: 18,
      replies: 8,
      views: 89,
      bookmarks: 15,
    },
    tags: ["solar-energy", "collaboration", "materials", "indonesia"],
    createdAt: "2024-01-14T14:20:00Z",
    updatedAt: "2024-01-15T09:15:00Z",
    isHot: false,
    isPinned: true,
    hasImage: false,
    lastActivity: "2024-01-15T09:15:00Z",
    lastActivityBy: "Dr. Lisa Handayani",
  },
  {
    id: "3",
    title: "Tips mendapatkan funding untuk riset early-stage",
    author: {
      name: "Dr. Budi Santoso",
      username: "budi_santoso",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face",
      role: "Biotech Researcher",
      institution: "Universitas Indonesia",
      reputation: 1890,
      badge: "Rising Star",
      verified: true,
    },
    category: "Funding",
    content:
      "Berbagi pengalaman tentang strategi mendapatkan funding untuk riset yang masih dalam tahap awal. Apa saja yang perlu dipersiapkan dan bagaimana meyakinkan investor?",
    stats: {
      likes: 45,
      replies: 23,
      views: 234,
      bookmarks: 32,
    },
    tags: ["funding", "startup", "investor", "early-stage"],
    createdAt: "2024-01-13T16:45:00Z",
    updatedAt: "2024-01-15T11:30:00Z",
    isHot: true,
    isPinned: false,
    hasImage: false,
    lastActivity: "2024-01-15T11:30:00Z",
    lastActivityBy: "Reza Firmansyah",
  },
  {
    id: "4",
    title: "Breakthrough: Penemuan material baru untuk baterai lithium yang lebih efisien",
    author: {
      name: "Dr. Maya Sari Putri",
      username: "maya_sari",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face",
      role: "Material Scientist",
      institution: "LIPI",
      reputation: 2890,
      badge: "Expert",
      verified: true,
    },
    category: "Materials Science",
    content:
      "Tim kami berhasil mengembangkan material katoda baru yang dapat meningkatkan kapasitas baterai lithium hingga 40%. Ini adalah terobosan besar untuk industri EV di Indonesia!",
    stats: {
      likes: 67,
      replies: 34,
      views: 445,
      bookmarks: 28,
    },
    tags: ["battery", "lithium", "materials", "ev", "breakthrough"],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T13:45:00Z",
    isHot: true,
    isPinned: true,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T13:45:00Z",
    lastActivityBy: "Prof. Bambang Susilo",
  },
  {
    id: "5",
    title: "Implementasi IoT untuk smart farming: Pengalaman 6 bulan di lapangan",
    author: {
      name: "Ir. Andi Wijaya",
      username: "andi_wijaya",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&crop=face",
      role: "IoT Engineer",
      institution: "Universitas Gadjah Mada",
      reputation: 1650,
      badge: "Industry Expert",
      verified: true,
    },
    category: "IoT",
    content:
      "Sharing hasil implementasi sistem IoT untuk monitoring tanaman padi di 50 hektar sawah. Data menunjukkan peningkatan yield 25% dan penghematan air 30%.",
    stats: {
      likes: 52,
      replies: 19,
      views: 298,
      bookmarks: 41,
    },
    tags: ["iot", "smart-farming", "agriculture", "sensors", "data"],
    createdAt: "2024-01-14T11:20:00Z",
    updatedAt: "2024-01-15T10:15:00Z",
    isHot: true,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T10:15:00Z",
    lastActivityBy: "Dr. Siti Nurhaliza",
  },
  {
    id: "6",
    title: "Kolaborasi riset blockchain untuk supply chain transparency",
    author: {
      name: "Prof. Bambang Susilo",
      username: "bambang_susilo",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      role: "Blockchain Researcher",
      institution: "Universitas Indonesia",
      reputation: 3450,
      badge: "Mentor",
      verified: true,
    },
    category: "Blockchain",
    content:
      "Mencari partner untuk mengembangkan sistem blockchain yang dapat melacak supply chain produk pertanian dari petani hingga konsumen. Target: transparansi 100%.",
    stats: {
      likes: 31,
      replies: 15,
      views: 187,
      bookmarks: 22,
    },
    tags: ["blockchain", "supply-chain", "transparency", "agriculture"],
    createdAt: "2024-01-13T09:30:00Z",
    updatedAt: "2024-01-14T16:20:00Z",
    isHot: false,
    isPinned: false,
    hasImage: false,
    lastActivity: "2024-01-14T16:20:00Z",
    lastActivityBy: "Fitri Handayani",
  },
  {
    id: "7",
    title: "Update: Hasil uji klinis obat herbal untuk diabetes tipe 2",
    author: {
      name: "Dr. Fitri Handayani",
      username: "fitri_handayani",
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face",
      role: "Pharmaceutical Researcher",
      institution: "Universitas Airlangga",
      reputation: 2100,
      badge: "Expert",
      verified: true,
    },
    category: "Healthcare",
    content:
      "Hasil fase II uji klinis menunjukkan ekstrak daun insulin dapat menurunkan gula darah 35% tanpa efek samping signifikan. Siap masuk fase III!",
    stats: {
      likes: 89,
      replies: 42,
      views: 567,
      bookmarks: 56,
    },
    tags: ["healthcare", "diabetes", "herbal", "clinical-trial", "pharmaceutical"],
    createdAt: "2024-01-12T14:15:00Z",
    updatedAt: "2024-01-15T08:30:00Z",
    isHot: true,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T08:30:00Z",
    lastActivityBy: "Dr. Ahmad Rahman",
  },
  {
    id: "8",
    title: "Diskusi: Etika AI dalam pengambilan keputusan medis",
    author: {
      name: "Dr. Siti Nurhaliza",
      username: "siti_nurhaliza",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face",
      role: "AI Ethics Researcher",
      institution: "Universitas Indonesia",
      reputation: 1980,
      badge: "Rising Star",
      verified: true,
    },
    category: "AI Ethics",
    content:
      "Dengan semakin banyaknya AI yang digunakan dalam diagnosis medis, bagaimana kita memastikan keputusan yang dibuat tetap etis dan dapat dipertanggungjawabkan?",
    stats: {
      likes: 38,
      replies: 27,
      views: 312,
      bookmarks: 19,
    },
    tags: ["ai-ethics", "healthcare", "medical-ai", "responsibility"],
    createdAt: "2024-01-14T16:00:00Z",
    updatedAt: "2024-01-15T12:45:00Z",
    isHot: false,
    isPinned: false,
    hasImage: false,
    lastActivity: "2024-01-15T12:45:00Z",
    lastActivityBy: "Prof. Dr. Indira Sari",
  },
  {
    id: "9",
    title: "Pengumuman: Grant Rp 5M untuk riset climate change adaptation",
    author: {
      name: "Admin ProyekSiswa",
      username: "admin_proyeksiswa",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      role: "Platform Admin",
      institution: "ProyekSiswa.id",
      reputation: 5000,
      badge: "Official",
      verified: true,
    },
    category: "Announcement",
    content:
      "Kementerian Lingkungan Hidup membuka grant hingga Rp 5 miliar untuk riset adaptasi perubahan iklim. Deadline: 31 Januari 2024. Info lengkap di thread ini!",
    stats: {
      likes: 156,
      replies: 78,
      views: 892,
      bookmarks: 134,
    },
    tags: ["grant", "climate-change", "funding", "announcement", "government"],
    createdAt: "2024-01-15T07:00:00Z",
    updatedAt: "2024-01-15T15:20:00Z",
    isHot: true,
    isPinned: true,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1569163139394-de44cb5894c6?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T15:20:00Z",
    lastActivityBy: "Dr. Environmental Scientist",
  },
  {
    id: "10",
    title: "Tutorial: Setup lab bioinformatika dengan budget terbatas",
    author: {
      name: "Dr. Reza Firmansyah",
      username: "reza_firmansyah",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face",
      role: "Bioinformatics Researcher",
      institution: "Institut Pertanian Bogor",
      reputation: 1450,
      badge: "Contributor",
      verified: true,
    },
    category: "Tutorial",
    content:
      "Step-by-step guide untuk setup lab bioinformatika dengan budget under 50 juta. Termasuk hardware recommendations, software stack, dan best practices.",
    stats: {
      likes: 73,
      replies: 31,
      views: 445,
      bookmarks: 67,
    },
    tags: ["bioinformatics", "lab-setup", "budget", "tutorial", "hardware"],
    createdAt: "2024-01-13T13:30:00Z",
    updatedAt: "2024-01-14T09:45:00Z",
    isHot: false,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=200&fit=crop",
    lastActivity: "2024-01-14T09:45:00Z",
    lastActivityBy: "Lab Manager UGM",
  },
  {
    id: "11",
    title: "Breaking: Indonesia masuk top 10 negara dengan publikasi AI terbanyak",
    author: {
      name: "Science News Indonesia",
      username: "science_news_id",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face",
      role: "Science Journalist",
      institution: "Science News Indonesia",
      reputation: 2340,
      badge: "Media Partner",
      verified: true,
    },
    category: "News",
    content:
      "Menurut laporan Nature Index 2024, Indonesia naik 5 peringkat menjadi posisi ke-8 dalam publikasi riset AI. Kontribusi terbesar dari ITB, UI, dan UGM.",
    stats: {
      likes: 234,
      replies: 89,
      views: 1245,
      bookmarks: 78,
    },
    tags: ["news", "ai", "indonesia", "research", "ranking", "publication"],
    createdAt: "2024-01-15T06:30:00Z",
    updatedAt: "2024-01-15T14:15:00Z",
    isHot: true,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T14:15:00Z",
    lastActivityBy: "Prof. AI Indonesia",
  },
  {
    id: "12",
    title: "Mencari beta tester untuk aplikasi mental health berbasis AI",
    author: {
      name: "Startup HealthTech",
      username: "healthtech_startup",
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face",
      role: "Startup Founder",
      institution: "MindCare AI",
      reputation: 890,
      badge: "Startup",
      verified: false,
    },
    category: "Beta Testing",
    content:
      "Kami mengembangkan aplikasi AI untuk deteksi dini gangguan mental health. Mencari 100 beta tester dari kalangan akademisi dan praktisi kesehatan.",
    stats: {
      likes: 45,
      replies: 67,
      views: 234,
      bookmarks: 23,
    },
    tags: ["beta-testing", "mental-health", "ai", "healthcare", "startup"],
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-15T11:20:00Z",
    isHot: false,
    isPinned: false,
    hasImage: false,
    lastActivity: "2024-01-15T11:20:00Z",
    lastActivityBy: "Dr. Psikolog Klinis",
  },
  {
    id: "13",
    title: "Workshop: Deep Learning untuk Computer Vision - Batch 3",
    author: {
      name: "AI Academy Indonesia",
      username: "ai_academy_id",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
      role: "Education Partner",
      institution: "AI Academy Indonesia",
      reputation: 1560,
      badge: "Education Partner",
      verified: true,
    },
    category: "Workshop",
    content:
      "Workshop intensif 3 hari tentang implementasi deep learning untuk computer vision. Hands-on dengan TensorFlow dan PyTorch. Early bird: 50% off!",
    stats: {
      likes: 67,
      replies: 45,
      views: 389,
      bookmarks: 89,
    },
    tags: ["workshop", "deep-learning", "computer-vision", "tensorflow", "pytorch"],
    createdAt: "2024-01-13T08:15:00Z",
    updatedAt: "2024-01-14T15:30:00Z",
    isHot: false,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=200&fit=crop",
    lastActivity: "2024-01-14T15:30:00Z",
    lastActivityBy: "Workshop Participant",
  },
  {
    id: "14",
    title: "Hasil survey: Tantangan terbesar researcher Indonesia di 2024",
    author: {
      name: "Research Indonesia",
      username: "research_indonesia",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face",
      role: "Research Organization",
      institution: "Research Indonesia",
      reputation: 2890,
      badge: "Organization",
      verified: true,
    },
    category: "Survey Results",
    content:
      "Survey terhadap 1000+ researcher Indonesia menunjukkan: 1) Funding (78%), 2) Akses jurnal internasional (65%), 3) Kolaborasi internasional (52%). Diskusi solusi?",
    stats: {
      likes: 123,
      replies: 156,
      views: 678,
      bookmarks: 45,
    },
    tags: ["survey", "research", "indonesia", "challenges", "funding"],
    createdAt: "2024-01-12T15:45:00Z",
    updatedAt: "2024-01-15T09:30:00Z",
    isHot: true,
    isPinned: false,
    hasImage: true,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=200&fit=crop",
    lastActivity: "2024-01-15T09:30:00Z",
    lastActivityBy: "Senior Researcher",
  },
  {
    id: "15",
    title: "Kolaborasi internasional: Joint research dengan MIT dan Stanford",
    author: {
      name: "Prof. Dr. Indira Sari",
      username: "indira_sari",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face",
      role: "International Collaborator",
      institution: "Institut Teknologi Bandung",
      reputation: 4200,
      badge: "International Expert",
      verified: true,
    },
    category: "International Collaboration",
    content:
      "Excited to announce joint research project dengan MIT dan Stanford tentang quantum computing applications. Looking for PhD students yang tertarik join!",
    stats: {
      likes: 189,
      replies: 67,
      views: 567,
      bookmarks: 123,
    },
    tags: ["international", "collaboration", "mit", "stanford", "quantum-computing"],
    createdAt: "2024-01-15T12:00:00Z",
    updatedAt: "2024-01-15T16:45:00Z",
    isHot: true,
    isPinned: true,
    hasImage: false,
    lastActivity: "2024-01-15T16:45:00Z",
    lastActivityBy: "PhD Candidate",
  },
]

export const communityNews = [
  {
    id: "news1",
    title: "Kementerian Riset Luncurkan Program Akselerasi Startup Teknologi",
    summary: "Program senilai Rp 100 miliar untuk mendukung 500 startup teknologi Indonesia",
    category: "Government",
    date: "2024-01-15T09:00:00Z",
    source: "Kemenristek",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=300&h=200&fit=crop",
  },
  {
    id: "news2",
    title: "Universitas Indonesia Raih Peringkat 1 ASEAN untuk Riset AI",
    summary: "UI unggul dalam publikasi dan sitasi riset artificial intelligence",
    category: "Achievement",
    date: "2024-01-14T14:30:00Z",
    source: "QS World University Rankings",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=200&fit=crop",
  },
  {
    id: "news3",
    title: "Breakthrough: Vaksin Malaria Buatan Indonesia Masuk Fase III",
    summary: "Hasil uji klinis menunjukkan efektivitas 89% dalam mencegah malaria",
    category: "Healthcare",
    date: "2024-01-13T11:15:00Z",
    source: "Bio Farma",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=300&h=200&fit=crop",
  },
]

export const categories = [
  { id: "all", name: "Semua", count: 156, color: "bg-gray-100" },
  { id: "ai", name: "Artificial Intelligence", count: 45, color: "bg-blue-100" },
  { id: "renewable-energy", name: "Renewable Energy", count: 28, color: "bg-green-100" },
  { id: "healthcare", name: "Healthcare", count: 32, color: "bg-red-100" },
  { id: "materials", name: "Materials Science", count: 23, color: "bg-purple-100" },
  { id: "iot", name: "IoT & Smart Systems", count: 19, color: "bg-orange-100" },
  { id: "blockchain", name: "Blockchain", count: 15, color: "bg-yellow-100" },
  { id: "funding", name: "Funding & Investment", count: 34, color: "bg-emerald-100" },
  { id: "collaboration", name: "Collaboration", count: 28, color: "bg-pink-100" },
  { id: "news", name: "News & Updates", count: 42, color: "bg-indigo-100" },
  { id: "tutorial", name: "Tutorial & Guide", count: 18, color: "bg-cyan-100" },
  { id: "announcement", name: "Announcements", count: 12, color: "bg-rose-100" },
]

export const topContributors = [
  {
    name: "Prof. Dr. Indira Sari",
    username: "indira_sari",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face",
    role: "International Collaborator",
    institution: "Institut Teknologi Bandung",
    contributions: 189,
    reputation: 4200,
    badge: "International Expert",
    verified: true,
  },
  {
    name: "Prof. Ahmad Fauzi",
    username: "ahmad_fauzi",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&crop=face",
    role: "Energy Researcher",
    institution: "Institut Teknologi Bandung",
    contributions: 167,
    reputation: 3200,
    badge: "Mentor",
    verified: true,
  },
  {
    name: "Dr. Maya Sari Putri",
    username: "maya_sari",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face",
    role: "Material Scientist",
    institution: "LIPI",
    contributions: 145,
    reputation: 2890,
    badge: "Expert",
    verified: true,
  },
  {
    name: "Dr. Sarah Wijaya",
    username: "sarah_wijaya",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=60&h=60&fit=crop&crop=face",
    role: "AI Researcher",
    institution: "Institut Teknologi Bandung",
    contributions: 134,
    reputation: 2450,
    badge: "Expert",
    verified: true,
  },
  {
    name: "Science News Indonesia",
    username: "science_news_id",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face",
    role: "Science Journalist",
    institution: "Science News Indonesia",
    contributions: 123,
    reputation: 2340,
    badge: "Media Partner",
    verified: true,
  },
]

export const trendingTopics = [
  { name: "AI Ethics", posts: 23, growth: "+15%" },
  { name: "Climate Tech", posts: 34, growth: "+28%" },
  { name: "Quantum Computing", posts: 12, growth: "+45%" },
  { name: "Biotech Innovation", posts: 28, growth: "+12%" },
  { name: "Smart Agriculture", posts: 19, growth: "+22%" },
]

export const recentActivities = [
  {
    type: "new_discussion",
    user: "Prof. Dr. Indira Sari",
    action: "memulai diskusi baru",
    target: "Kolaborasi internasional: Joint research dengan MIT dan Stanford",
    time: "5 menit lalu",
  },
  {
    type: "reply",
    user: "Dr. Ahmad Rahman",
    action: "membalas diskusi",
    target: "Hasil uji klinis obat herbal untuk diabetes tipe 2",
    time: "12 menit lalu",
  },
  {
    type: "like",
    user: "Prof. Bambang Susilo",
    action: "menyukai diskusi",
    target: "Breakthrough: Penemuan material baru untuk baterai lithium",
    time: "18 menit lalu",
  },
  {
    type: "new_member",
    user: "Dr. Researcher Baru",
    action: "bergabung dengan komunitas",
    target: "",
    time: "25 menit lalu",
  },
]
